/**********************************************************************
 Android-Freeciv - Copyright (C) 2010 - C Vaughn
   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
***********************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_hackcasual_freeciv_NativeHarness */

#ifndef _Included_net_hackcasual_freeciv_NativeHarness
#define _Included_net_hackcasual_freeciv_NativeHarness
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     net_hackcasual_freeciv_NativeHarness
 * Method:    startClient
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_hackcasual_freeciv_NativeHarness_startClient
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_net_hackcasual_freeciv_NativeHarness_init
  (JNIEnv *, jobject, jint, jint);

JNIEXPORT void JNICALL Java_net_hackcasual_freeciv_NativeHarness_step
  (JNIEnv *, jobject);

JNIEXPORT jbyteArray JNICALL Java_net_hackcasual_freeciv_NativeHarness_getAvailableCommandsForActiveUnit
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_net_hackcasual_freeciv_NativeHarness_sendNativeCommand
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_net_hackcasual_freeciv_NativeHarness_cityNameResponse
  (JNIEnv *, jobject, jstring, jint);



#ifdef __cplusplus
}
#endif
#endif
